$# LS-DYNA Keyword file created by LS-PrePost(R) V4.8.30 - 20Apr2022
$# Created on Nov-27-2023 (11:48:59)
*KEYWORD
*PARAMETER
$#   prmr1      val1     prmr2      val2     prmr3      val3     prmr4      val4
rtbumper  3         rtroof    2         rtrailb   2         rtrailf   2
rtgrill   1         rthood    1                                                 
*INCLUDE
$#                                                                      filename
car6_crash_v221.k
*END
