$# LS-DYNA Keyword file created by LS-PrePost(R) V4.8.30 - 20Apr2022
$# Created on Dec-1-2023 (15:23:08)
*KEYWORD
*PARAMETER
$#   prmr1      val1     prmr2      val2     prmr3      val3     prmr4      val4
rtbumper  5         rtroof    2         rtrailb   2         rtrailf   0.5
rtgrill   1         rthood    1                                                 
*INCLUDE
$#                                                                      filename
car6_crash_v222.k
*END
